project:
  type: website

website:
  title: "prog_practice"
  navbar:
    left:
      - href: index1m.qmd
        text: MTM-11 Programming Practice 
      - href: index2s.qmd
        text: MTS-21 Programming Practice 
      - href: index3s.qmd
        text: MTS-31 Programming Practice 
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



